#pragma once

#include <iostream>
#include <memory>
#include <string>
#include <vector>
#include <utility>
#include <algorithm>
#include <queue>
#include <limits>
#include <ranges>
#include <functional>
#include <print>
#include <format>
#include <map>
#include <random>
#include <stdexcept>
#include <exception>
#include <ranges>
#include <fstream>
#include <istream>
#include <sstream>
#include <regex>
#include <iostream>
#include <vector>
#include <queue>
#include <functional>
#include <atomic>
#include <thread>
#include <mutex>
#include <condition_variable>
#include <future>
#include <type_traits>
#include <chrono>
#include <unordered_map>

//#include "termcolor.hpp"